export enum DiagnosticsTypes {
    DPE = 'DPE',
    CARREZ_BOUTIN = 'CARREZ_BOUTIN',
    ELECTRICITE = 'ELECTRICITE',
    GAZ = 'GAZ',
    AMIANTE = 'AMIANTE',
    PLOMB = 'PLOMB',
    TERMITE_ETAT_PARASITAIRE = 'TERMITE_ETAT_PARASITAIRE',
    ERP = 'ERP',
    ASSAINISSEMENT = 'ASSAINISSEMENT',
    DTG = 'DTG',
    DPE_MENTION = 'DPE_MENTION'
}